service: poc-kotlin-lambda-serverless-api
org: rodtech

frameworkVersion: '3'

provider:
  name: aws
  runtime: java11

package:
  artifact: app/build/distributions/app.zip

functions:
  hello:
    handler: com.rodtech.serverless.ApiHandle
    events:
      - httpApi:
          path: /hello
          method: get