name: Poc kotlin AWS Lambda With Serverless

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-last
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        run: ./gradlew build